# Milestone 1

## Exploratory Data Analysis

In [1]:
import pandas as pd
import altair as alt

## Read the data

In [2]:
url = 'https://raw.githubusercontent.com/luckyberen/DSCI320_Project/main/spotify_tracks.csv'
data = pd.read_csv(url)
data.head()

,track_id,track_name,album_name,artist_1,artist_2,artist_3,artist_4,track_genre_1,track_genre_2,track_genre_3,...,duartion_s,popularity,danceability,loudness,speechiness,acousticness,instrumentalness,liveness,energy,valence
0,71ehTADpxs85ULrZgSEKCy,Almost Lover,One Cell In The Sea,A Fine Frenzy,NaN,NaN,NaN,acoustic,NaN,NaN,...,268.80,57,0.549,-7.778,0.0338,0.947,0.000000,0.1060,0.240,0.1670
1,2fPb58e6f8KxejYDCaARwS,Say Something,Is There Anybody Out There?,A Great Big World,NaN,NaN,NaN,acoustic,piano,NaN,...,233.27,57,0.447,-7.571,0.0360,0.872,0.000002,0.0816,0.158,0.1420
2,6Vc5wAMmXdKIAM7WUoEb7N,Say Something,Is There Anybody Out There?,A Great Big World,Christina Aguilera,NaN,NaN,acoustic,piano,NaN,...,229.40,74,0.407,-8.822,0.0355,0.857,0.000003,0.0913,0.147,0.0765
3,7xLhousIHDxoGgeJNhO4Ye,Say Something,Is There Anybody Out There? - Track by Track C...,A Great Big World,NaN,NaN,NaN,acoustic,piano,NaN,...,233.27,57,0.447,-7.571,0.0360,0.872,0.000002,0.0816,0.158,0.1420
4,0jJqIi0uMG8IhGlLx7U85J,Already Home,Is There Anybody Out There? - Track by Track C...,A Great Big World,NaN,NaN,NaN,acoustic,NaN,NaN,...,230.19,44,0.602,-7.344,0.0272,0.310,0.000000,0.1400,0.404,0.2430

## Summary of each variable

In [3]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89741 entries, 0 to 89740
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          89741 non-null  object
 1   track_name        89740 non-null  object
 2   album_name        89740 non-null  object
 3   artist_1          89740 non-null  object
 4   artist_2          22584 non-null  object
 5   artist_3          6784 non-null   object
 6   artist_4          2124 non-null   object
 7   track_genre_1     89741 non-null  object
 8   track_genre_2     16641 non-null  object
 9   track_genre_3     4929 non-null   object
 10  track_genre_4     1945 non-null   object
 11  track_genre_5     573 non-null    object
 12  explicit          89741 non-null  bool
 13  mode              89741 non-null  object
 14  key               89741 non-null  object
 15  time_signature    89741 non-null  int64
 16  tempo             89741 non-null  float64
 17  duartion_s        89741 non-null  float64
 18  popularity        89741 non-null  int64
 19  danceability      89741 non-null  float64
 20  loudness          89741 non-null  float64
 21  speechiness       89741 non-null  float64
 22  acousticness      89741 non-null  float64
 23  instrumentalness  89741 non-null  float64
 24  liveness          89741 non-null  float64
 25  energy            89741 non-null  float64
 26  valence           89741 non-null  float64
dtypes: bool(1), float64(10), int64(2), object(14)
memory usage: 17.9+ MB
None

In [4]:
data.describe()

,time_signature,tempo,duartion_s,popularity,danceability,loudness,speechiness,acousticness,instrumentalness,liveness,energy,valence
count,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000,89741.000000
mean,3.897427,122.058304,229.142024,33.198750,0.562166,-8.499004,0.087442,0.328289,0.173413,0.216970,0.634458,0.469477
std,0.453435,30.117515,112.947758,20.581255,0.176691,5.221490,0.113277,0.338321,0.323848,0.194884,0.256605,0.262864
min,0.000000,0.000000,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,99.260000,173.040000,19.000000,0.450000,-10.322000,0.036000,0.017100,0.000000,0.098200,0.457000,0.249000
50%,4.000000,122.010000,213.290000,33.000000,0.576000,-7.185000,0.048900,0.188000,0.000058,0.132000,0.676000,0.457000
75%,4.000000,140.080000,264.290000,49.000000,0.692000,-5.108000,0.085900,0.625000,0.097600,0.279000,0.853000,0.682000
max,5.000000,243.370000,5237.300000,100.000000,0.985000,4.532000,0.965000,0.996000,1.000000,1.000000,1.000000,0.995000

## Visualizations of variables

### Nominal variables

In [ ]:
alt.data_transformers.disable_max_rows()


plot_nominal = alt.Chart(data).mark_bar().encode(
    alt.X(alt.repeat('repeat'), type='nominal'),
    alt.Y('count()')
).properties(
  width=200,
  height=200
).repeat(
  data=data,
  repeat = ['explicit','mode','key', 'time_signature'],
  columns = 2
)


plot_nominal

## Quantitative variables

In [ ]:
plot_quantitative = alt.Chart(data).mark_bar().encode(
    alt.X(alt.repeat('repeat'), type='quantitative',bin=alt.BinParams(maxbins=30)),
    alt.Y('count()')
).properties(
  width=200,
  height=200
).repeat(
  data=data,
  repeat = ['tempo','duartion_s','popularity','danceability','loudness','speechiness','acousticness',
            'instrumentalness','liveness','energy','valence'],
  columns = 3
)
plot_quantitative

## Bi-variable Visualizations

In [ ]:
# plot_bivari = alt.Chart(data).mark_circle().encode(
#     alt.X(alt.repeat('row'),type='quantitative'),
#     alt.Y(alt.repeat('column'),type='quantitative'),
# ).properties(
#   width=200,
#   height=200
# ).repeat(
#   data=data,
#   row = ['tempo','danceability','loudness','popularity'],
#   column = ['popularity','loudness','danceability','tempo']
# )
# plot_bivari